### ISSUE TITLE
Create an issue template

### ISSUE THREAD

**Issue by FelixTJDietrich** [pal03377/Athena-New#287]
We are missing an issue template when creating issues.

**Comment by DominikRemo** [comment]
## Issue Template

### Description


### Steps to Reproduce (for bugs)
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error

### Expected Behavior


### Actual Behavior


### Screenshots


### Environment
- **OS:** [e.g. Windows, macOS, Linux]
- **Browser:** [e.g. Chrome, Firefox, Safari]
- **Version:** [e.g. v1.0.0]

### Additional Context

**Comment by FelixTJDietrich** [comment]
Looks roughly okay, maybe we can conditionally ask for the browser using:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

I also don't know if we have release versions of Athena. Maybe we create an issue to tackle if release management makes sense. 

We could also have (multi-)select for the affected modules or if it is a playground issue.

I think it would be good to have multiple issue templates:
- Bug Report
- Feature Request
- Custom Template (No template)

I don't know if something like `Feature Proposal (Developer)` makes sense 🤔 
Maybe just open a PR with the issue template(s) and we can further discuss it there.
